# Generated by Django 4.2.4 on 2023-09-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date_added',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('WEP', 'Weapons'), ('ARM', 'Armors'), ('CON', 'Consumables'), ('MAG', 'Magic Items'), ('MIS', 'Miscellaneous')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
