# Generated by Django 4.2.4 on 2023-09-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_item_date_added_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Weapons', 'Weapons'), ('Armors', 'Armors'), ('Consumables', 'Consumables'), ('Magic Items', 'Magic Items'), ('Miscellaneous', 'Miscellaneous')], max_length=255),
        ),
    ]
